### ISSUE TITLE
TypeError at Parser line 77

### ISSUE THREAD

**Issue by guyappy** [felixge/node-mysql#1345] opened 2016-02-10 14:33 UTC
Dear NodeMySQL team,

I'm running into the following error. It's only experienced when deployed on a server so it's difficult for me to debug this. Cna you please provide some guidance on how to solve this or what this problem might be?

`	*** TypeError: Expected argument of type object, but instead had type string TypeError: Expected argument of type object, but instead had type string at /organization/environment/api/node_modules/mysql/lib/protocol/Parser.js:77 at /organization/environment/api/node_modules/mysql/lib/protocol/Protocol.js:39 at /organization/environment/api/node_modules/mysql/lib/Connection.js:96 at emit (events.js:95) at _stream_readable.js:764 at emit (events.js:92) at emitReadable_ (_stream_readable.js:426) at emitReadable (_stream_readable.js:422) at readableAddChunk (_stream_readable.js:165) at _stream_readable.js:127 at onread (net.js:528)
`
thanks a million!

**Comment by dougwilson** [comment] 2016-02-10 21:39
Weird. Can you provide code that I can use to reproduce the issue? 

I looked at the line you referenced, https://github.com/felixge/node-mysql/blob/master/lib/protocol/Parser.js#L77, and that line just re-throws an exception from code outside of this library, so it's probably critical to get the code I can run to reproduce the issue in order to pinpoint where the error is coming from.

**Comment by guyappy** [comment] 2016-02-11 16:57
Hi Doug,

Thanks for that confirmation and the quick response! The problem only occurs when uploading the code to a particular server, so probably on that server there is something wrong with the connectivity or something. I'll investigate this quickly tomorrow.

**Comment by Etzos** [comment] 2016-02-12 23:04
I have a similar, but possibly related issue. The error happens at the same place but the error is slightly different so I'm not sure if it's the same. Anyway, the error I get is:

> TypeError: Cannot read property '2' of null

I have been able to reproduce this to a degree. I don't have time to come up with a simple test case for you, I might do it over the weekend if I can. The common thing that I found was when trying to insert a string value that ended in the number three (3) the error will always happen. However I haven't been able to test with a raw query, on another table, or even on another database yet. Just thought I'd add in what I found so far.

**Comment by guyappy** [comment] 2016-02-15 08:44
Hi Doug,

Can I change the module perhaps so that the exception from outside the library is thrown instead of the mysql lib rethrowing the exception?

**Comment by dougwilson** [comment] 2016-02-15 23:54
Hi @guyappy, I assume this means you've determined that the issue is in your code, rather than the library? I'm going to close this issue for now unless you can prove a fix or example of how to reproduce your issue.

> Can I change the module perhaps so that the exception from outside the library is thrown instead of the mysql lib rethrowing the exception?

I'm not sure what you mean by that question. Your callback is called from within a `try...catch` block in this module's code. The way the module is currently written, you can't change that, but it also means that your error will invoke our `catch` if you don't use your own `try...catch` in your callback. Because we don't know how to handle your errors, we just re-throw the error with the JavaScript language mechanisms.

I'm no sure where you pulled that stack trace, but it perhaps seems like whatever you are using to capture the exception is what is buggy, and doesn't understand re-thrown errors or something. If you can provide code to reproduce that, that would help me provide a better answer.

**Closed by dougwilson** 2016-02-15 23:54 UTC
Labels: question
