### ISSUE TITLE
no response with node 0.12.6

### ISSUE THREAD

**Issue by wiiny** [felixge/node-mysql#1153] opened 2015-07-17 16:50 UTC
Hi,
I created a pool connection with node-mysql v2.8.0 (same result in v2.5.1).
I use steam and pipe, but I have no error et no response after a few seconds. The process node is still running a few minutes, but no activity.
I tried to downgrade nodejs to v0.10.39 and then it's OK.
I think there is a problem between nodejs 0.12.6 et node-mysql v2.8.0 but I don't know why...
I hope I can help...

**Comment by dougwilson** [comment] 2015-07-17 16:56
Hi! We've been getting reports that at least SSL in Node.js 0.12 has been broken. Not sure if Node.js 0.12 broke anything extra. Can you try on like 0.12.1 or something to try to narrow down if your issue is related to a regression in one of the 0.12 releases?

**Comment by dougwilson** [comment] 2015-07-18 23:46
Hi @wiiny , any update on trying a different version of Node.js 0.12, like 0.12.1, for example, so we can determine if this is a regression in Node.js 012?

**Comment by wiiny** [comment] 2015-07-18 23:52
Hi, i Will try it this monday.

**Comment by wiiny** [comment] 2015-07-22 14:30
Hi,
I'm wrong. I have same troubles in 0.10.38 and 0.10.39.
Some logs : 
Error: Connection lost: The server closed the connection.
        at Protocol.end (/home/user/project/node_modules/mysql/lib/protocol/Protocol.js:103:13)
        at Socket.<anonymous> (/home/user/project/node_modules/mysql/lib/Connection.js:102:28)
        at Socket.emit (events.js:117:20)
        at _stream_readable.js:944:16
        at process._tickDomainCallback (node.js:492:13)
        --------------------
        at Pool.query (/home/user/project/node_modules/mysql/lib/Pool.js:191:23)
...

**Comment by dougwilson** [comment] 2015-07-22 14:44
That error is simply our module reporting that your MySQL server is closing the connection for whatever reason. This could be a network issue or you have left your connection longer than your server's configured idle time.

**Comment by dougwilson** [comment] 2015-07-22 14:45
Basically, that error does not seem at all related to the initial issue on Node.js 0.12. Where you able to do the 0.12 tests yet?

**Comment by wiiny** [comment] 2015-07-22 15:19
Sorry, I'm wrong, again.
In 0.12.0 and 0.12.6, I have no response after a few seconds.
My problem in 0.10 is an other problem (no reconnection after 10 minutes).

**Comment by wiiny** [comment] 2015-07-23 20:21
I resolved my second problem (server connection closed alter 10minutes).
So I confirm that I have no response after a few senconds with node v0.12.0 and 0.12.6.
You're right : at least SSL in Node.js 0.12 has been broken.

**Comment by dougwilson** [comment] 2015-08-12 06:10
Hi @wiiny so you think there is anything further we can help with? I'm not sure how many people actually use Node.js 0.12, with all the confirmed bugs with it and the non-attention it seems to have lately, but if there is a way to fix the issue with a PR, please do submit one to us!

**Comment by wiiny** [comment] 2015-08-12 09:04
Hi
You have to add a last pipe wich mustn't make any push.

**Comment by kazazes** [comment] 2015-08-13 20:03
I'm having a similar issue. If I perform the query without using a stream, I receive results just fine. However, when using a stream, I see some significant network traffic and then receive the end event in less than a few seconds. My node version is 0.12.7. Trying on a different version now.

**Comment by kazazes** [comment] 2015-08-13 20:20
Switching node to 0.12.1 had no effect. Weirdly, node-inspector shows that node-mysql received the field names, but the field event never fires.
<img width="1154" alt="" src="https://cloud.githubusercontent.com/assets/938406/9260630/e63313e2-41d6-11e5-986f-72958512da1c.png">

**Comment by kazazes** [comment] 2015-08-13 21:13
I logged the buffers to the console and it turns out the data is being sent and the query executed, but only the end event is fired.
<img width="885" alt="screen shot 2015-08-13 at 17 12 34" src="https://cloud.githubusercontent.com/assets/938406/9261836/a3ab1f62-41de-11e5-9e0c-dbb5caed4177.png">

**Comment by dougwilson** [comment] 2015-08-13 21:19
AFAIK there is no `fields` event in this library. I see it's in one of the examples in the readme, so I think it's there in error.

**Comment by dougwilson** [comment] 2015-08-13 21:20
Nevermind, I was thinking of a different library, sorry!

**Comment by kazazes** [comment] 2015-08-13 22:19
I've isolated the issue and am working on a fix now and will PR when complete. Even when a query is created with no callback, one is being added. When data is received, the library checks if a callback exists to determine whether or not to emit an event, and, since an empty callback is added, the events are never emitted.

**Comment by kazazes** [comment] 2015-08-13 22:29
It's the function wrappers fault -- using this method signature works, instead of what's in the documentation: `connection.query(sql, values, undefined);`

**Comment by dougwilson** [comment] 2015-08-13 22:58
Ah. New Relic has specific code for wrapping this module at https://github.com/newrelic/node-newrelic/blob/master/lib/instrumentation/mysql.js

You'll need to get New Relic to fix the wrapper, or use that work-around, I would surmise.

**Comment by evanhuang8** [comment] 2015-09-03 19:22
Similar issue here, when using iojs 1.x I can connect OK, but once I use iojs 2.x it just hangs

**Comment by dougwilson** [comment] 2015-09-03 19:33
Hi @evanhuang8 unlesss you are dealing with the New Relic issue (which New Relic will need to fix), I cannot replicate hangs as well as Travis CI, which runs all those versions of io.js does not hang. Without a replication from someone, we cannot do anything :( Please provide a full detailed way to reproduce the issue, or better yet, a PR that fixes it :)

**Comment by evanhuang8** [comment] 2015-09-03 19:50
Hi @dougwilson New Relic isn't the issue for me - my setup is as follows:

I have a MySQL instance running locally, and using the following command I can connect to the db fine:

`mysql -u app -p mypassword --ssl-ca=/path/to/my/cert.crt`

So I basically created a simple test script that is copied from the `node-mysql` examples:

```javascript
var mysql      = require('mysql');
var fs = require('fs');
var path = require('path');
var connection = mysql.createConnection({
  host     : 'localhost',
  user     : 'app',
  password : 'mypassword',
  database : 'mydb',
  ssl: {
    ca: fs.readFileSync('/path/to/my/cert.crt', 'utf8')
  },
  debug: true,
  trace: true
});

connection.connect();

connection.query('SELECT 1 + 1 AS solution', function(err, rows, fields) {
  if (err) throw err;

  console.log('The solution is: ', rows[0].solution);
});

connection.end();
```

I used nvm to iterate through different versions of iojs: `1.8.1`, `2.0.0`, `2.2.1`, `2.3.0`, `2.3.4`, `2.5.0`, `3.3.0`...

All versions up to `2.2.1` runs the script fine, solution is printed out. However, for all versions >= `2.3.0`, the script hangs. The trace shows only these two packets are sent/received:

```
<-- HandshakeInitializationPacket
{ protocolVersion: 10,
  serverVersion: '5.6.25-log',
  threadId: 357,
  scrambleBuff1: <Buffer 7e 26 41 52 5b 50 5d 66>,
  filler1: <Buffer 00>,
  serverCapabilities1: 65535,
  serverLanguage: 8,
  serverStatus: 2,
  serverCapabilities2: 49279,
  scrambleLength: 21,
  filler2: <Buffer 00 00 00 00 00 00 00 00 00 00>,
  scrambleBuff2: <Buffer 67 54 4f 6f 60 73 44 35 7d 3b 4a 42>,
  filler3: <Buffer 00>,
  pluginData: 'mysql_native_password',
  protocol41: true }

--> SSLRequestPacket
{ clientFlags: 457679, maxPacketSize: 0, charsetNumber: 33 }
```

My guess is the changes in openssl broke it at `2.3.0`? Here's the change log for that version: https://github.com/nodejs/node/blob/master/CHANGELOG.md#2015-06-13-version-230-rvagg

Let me know if I can provide more details!

**Comment by dougwilson** [comment] 2015-09-03 20:03
Hi @evanhuang8 , thanks for the additional info! A change from 2.2.1 to 2.3.0 should not break things like our module, or it's a violation of the semver contract. It's possible that io.js has a legitimate regression that this is uncovering? Any possibility of checking it out to see if you can get a PR together?

**Comment by dougwilson** [comment] 2015-09-03 20:06
Also, there was a report not too long ago that said io.js did something with their OpenSSL that broke support for MySQL servers below 5.7. Perhaps that is what this is?

**Comment by evanhuang8** [comment] 2015-09-03 20:21
I would be happy to look into it, since it's a huge roadblock for me as well. However, I am still pretty green when it comes to the node/iojs run time. I will update if I find out anything.

**Comment by evanhuang8** [comment] 2015-09-03 20:21
Would you be able to find that report?

**Comment by evanhuang8** [comment] 2015-09-03 22:14
@dougwilson your guess was right. Apparently the openssl upgrade mandates the DH key to be at least 1024-bit long, while older version of MySQL (< `5.6.25`, which was what I had) has a key length of 512 bit. 

See this issue: https://bugzilla.redhat.com/show_bug.cgi?id=1228755

I upgraded MySQL to `5.6.26` and the problem is fixed. You might consider adding a note for future reference?

**Comment by dougwilson** [comment] 2015-09-03 22:25
Ah, nice. I'll add the note, but will wait for io.js to fix the issue first. There should be an error, not just a hang. Most people will never see this note in our documentation, so we need to have a way to provide an error to the callback.

Can you file an issue over at the io.js project for the hang?

**Comment by dougwilson** [comment] 2016-01-12 19:53
I'm not sure if you ever opened that issue, but I was able to work-around the hang by using an undocumented event in our code for the time being.

**Closed** 2016-01-12 20:03 UTC
Labels: bug
