### ISSUE TITLE
Problem with getConnection() failing to call back

### ISSUE THREAD

**Issue by CliffS** [felixge/node-mysql#1187] opened 2015-08-19 17:47 UTC
I maintain a list of pools for each database.  My code calls module.pool(options, database, cb) to acquire a connection.

    Pools = {}
    exports.pool = (options, database, callback) ->
      options.database = database
      pool = Pools[database] ?= MySQL.createPool options
      pool.getConnection (err, connection) ->
        throw err if err
        callback err, new Connection connection

On occasion, `pool.getConnection` fails to call back with either a connection or an error.  The relevant part of my Connection class is:

    class Connection
      constructor: (@conn) ->

      query: ->
        @conn.query.apply @conn, arguments

      release: ->
        @conn.release()

If I make `release()` a no-op, `getConnection()` always seems to work but, of course the pool fills up.

My work flow is to call `connection.release()` as the first line of the callback from `connection.query()` before accessing the `rows` parameter.  Is this reasonable?

Am I doing something stupid?  Should there ever be a time that `getConnection()` fails to call back?  I would mention that this happens in one case on the second call to `pool()` so it looks like there's a problem with re-use.

**Comment by dougwilson** [comment] 2015-08-19 18:13
Hm, it's unfortunately hard to say. So far this question has never had an answer other than "you forgot to call `conn.release()` is some obscure code path (i.e. you left connections hanging somewhere in the code).

Most likely the `getConnection` hangs because all your requests for a connection have been enqueued (you can tell by listening to the `enqueue` event https://github.com/felixge/node-mysql#enqueue) and everything is waiting for you to call `.release()` on some connection you have checked out from the pool.

Without full, complete code I can re to reproduce the issue, it's really hard to say without you debugging the reason :(

**Comment by CliffS** [comment] 2015-08-19 18:26
That was the reason for my wrapping the connection class into my own `Connection` class.  It means I can add a debugging line to see every connection and release.  The code currently reads:

        release: ->
        @conn.release()
        connections--
        console.log "release: #{connections}" if DEBUG

and

      connections++
      console.log "getConnection: #{connections} (total: #{++total})" if DEBUG
      pool.getConnection (err, connection) ->

The output in the one script which fails is:

    getConnection: 1 (total: 1)
    release: 0
    getConnection: 1 (total: 2)

and that's it!  It can't be an issue of failing to `release()` as (a) the debugging line shows up and (b) if I *don't* do the 'release()' the code works.

The oddest thing is that this only fails in one fairly simple script while it's running happily in other scripts and a server on the same machine.  I should probably have mentioned that I'm running under Node v0.12.7.

**Comment by dougwilson** [comment] 2015-08-19 18:29
Ah, gotcha. I don't understand CoffeeScript, so when you first posted that, I just glossed over it because I have no idea what it even means (like what does the `@` mean?). If you have a fairly simply script that fails, could you perhaps share the script?

**Comment by CliffS** [comment] 2015-08-19 18:40
Sorry, I should have converted it to Javascript.  `@conn` simply means `this.conn` and the constructor `constructor: (@conn) ->` translates to

    function Connection(conn) {
    this.conn = conn;
    }

The script calls quite deeply into a library but I'll see if I can extract out a simple case that fails.

**Comment by dougwilson** [comment] 2015-08-19 18:56
That'd be awesome!

**Comment by CliffS** [comment] 2015-08-20 18:00
OK.  After a day's worth of debugging with [node-inspector](https://www.npmjs.com/package/node-inspector), I found the problem.  The call to `pool.getConnection()` that was not receiving a callback had been called from within a function that had been [deasync](https://www.npmjs.com/package/deasync)ed.  Because of the way that this module calls the callback from deep in the `EventEmitter` module, it doesn't play well with deasync.  I think the event was not triggering but I got a bit lost.

I have now changed all my code to remove deasync and everything seems to be working.  Thanks for your help, Doug.  And thanks to all the contributors for such an excellent and well-written module.

**Comment by dougwilson** [comment] 2015-08-21 02:46
Very interesting! I've never heard of the `deasync` library before, but I'm going to leave this open because I want to at least take a look into it to see if there is something we can change to make it function with `deasync` (perhaps we are using EEs in some weird way).

**Comment by dougwilson** [comment] 2015-08-21 02:48
There is also a possibility that we may be encountering the bug https://github.com/abbr/deasync/issues/21

**Comment by dougwilson** [comment] 2016-01-13 00:38
Hi! I'm going to close this for now, because it seems to be an issue with the `deasync` library, and not anything in particular we are doing wrong with the Event Emitter interface. If you have any ideas for a pull request to us that makes sense, please feel free!

**Closed by dougwilson** 2016-01-13 00:38 UTC

**Comment by dfranusic** [comment] 2018-10-08 17:07
I just set `waitForConnections` to `false` and handled the rest myself. I guess that's the only viable solution. I am only commenting on this since it's almost 2019 and this issue is still present.
