### ISSUE TITLE
"The server closed the connection"

### ISSUE THREAD

**Issue by Rexota** [felixge/node-mysql#1337] opened 2016-01-31 08:17 UTC
`{ [Error: Connection lost: The server closed the connection.] fatal: true, code: 'PROTOCOL_CONNECTION_LOST' }`

I'm getting this error constantly. Why? Here is my connection class:

```js
var mysql      = require('mysql')

var db_config = {
  host     : '127.0.0.1', user     : 'root',  database : 'db',  password : 'pw'
}

module.exports = connection

var pool  = mysql.createPool(db_config)

pool.getConnection(function(err, connection) {
  console.log("getConnection:", err, connection)
});

module.exports = pool
```
I tried with `createConnection` too but still same. I read the README.md#pooling section but I didn't understand anything. Are there any guide etc? (If not, I'll have to move whole back-end to PHP.)

Thanks.

**Comment by Bigood** [comment] 2016-02-02 10:05
+1, same problem here. Can't find a solution, as I can't intercept the event and recreate the connection with the pooling.

**Comment by Rexota** [comment] 2016-02-02 22:09
Still searching for a permanent solution.

**Comment by Rexota** [comment] 2016-02-13 13:57
Still......

**Comment by Bigood** [comment] 2016-02-13 14:54
I solved it by reducing the number of maxConnections, so I'm sure that all the pooled connection are reused before they reach the idle_timeout of mysql (which is 8 hours by default).

For the record, I also had an init script at server launch, which created a connection prior to the pool creation, which was never closed - thus crashing the server systematically after 8 hours since boot time. Guilty!

I'd advise to double check that you don't create any connection out of the pool, and to use SHOW PROCESS_LIST to check if you have any pooled connection hanging there, waiting to be reused indefinitely (lower your maxConnections in this case)

**Comment by dougwilson** [comment] 2016-02-15 23:58
Hi @Rexota, the error is because of some kind of weird idle timeout setting on your server or even some kind of higher-level management closing the connection between the server and your code. I could take a closer look if you can provide some information for me to reproduce your issue, or perhaps more information?

**Comment by DoraEs** [comment] 2016-03-16 09:28
Hey people, hope you have resolved your problem by now. To answer the comment about not being able to intercept the error, you can do something like that : 

```
function mysqlQuery(query, cb) {    
    POOL.getConnection(function(err, connection) {
        if (err) {
            if(connection)
                connection.destroy();
            cb(err);
            return;
        }
        connection.query(query, function(err, rows) {
            connection.destroy();
            cb(err, rows);
            return;
        });

        connection.on('error', function(err) {
            DO WHATEVER HERE
        });
    });
}
```

`connection.release()` keeps the connection active and releases it into the pool to be used again when needed. But it times out after some time of inactivity.
`connection.destroy()` closes it. So the pool will need to create a new one each time but no time out. 

Hope that helps. switching from release to destroy fixed it for me. Not sure about the consequences of that performance-wise.

**Comment by seriousManual** [comment] 2016-04-20 10:46
running into this as well.
looking into the mysql code it looks like it would help attach an error handler to the connection object which would handle the disconnect? (the error bubbles up because no error handler is attached)

can somebody confirm this?

**Comment by dougwilson** [comment] 2016-04-20 16:36
I'm going to close this, because there is still nothing concrete here for us to help with.

@seriousManual the `Connection` object from our library is what we are exposing. You have to add an error listener to it yourself, nothing we can do. Perhaps I'm misunderstanding you or something else. If you have a hunch, please share a pull request :)

**Closed by dougwilson** 2016-04-20 16:36 UTC
Labels: question

**Comment by seriousManual** [comment] 2016-04-21 05:39
@dougwilson thanks, thats what I was asking about. my program crashed because of the error and i was not completely sure if the missing event handler was the cause of the crash.

thanks for your work!
