### ISSUE TITLE
Unable to connect to MySQL5.5 using password:NO

### ISSUE THREAD

**Issue by vdraceil** [felixge/node-mysql#1211] opened 2015-09-04 02:44 UTC
I'm able to connect to MySQL via command line - `mysql -u 'root'`. The 'root' user has no password set, so using `mysql -u 'root' -p ''` would not work and prompt for a password.

This is how I'm trying to connect to MySQL via Node
```
var conn = mysql.createConnection({
  host: 'localhost',
  user: 'root',
  database: 'db'
});
```
.. but all I'm getting is **ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)**
I'm getting the same error message when setting 'password' to '' in the connection.

`mysql -V` : mysql  Ver 14.14 Distrib 5.5.42, for Linux (x86_64) using readline 5.1

Am I missing something?
Can you please help me connect to MySQL with a user who has no password?

**Comment by dougwilson** [comment] 2015-09-04 03:01
Your command line you are using is connecting over a UNIX socket, while the MySQL command you are using here is connecting over TCP. This is likely the cause of your issue: MySQL grants also take into account how you are performing the connection in addition to the username and password.

You can always connect to your MySQL server using a UNIX socket instead of TCP, though. Run the following command on the server:
```bash
$ mysql_config --socket
/tmp/mysql.sock
```
Then take the value it gave you (`/tmp/mysql.sock` in this example) and give it to the `socketPath` option for this module:
```js
var connection = mysql.createConnection({
  socketPath : '/tmp/mysql.sock',
  user       : 'root',
  database   : 'db'
});
```

**Comment by vdraceil** [comment] 2015-09-04 03:17
I tried using **socketPath**, but I'm still seeing **ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)**

Here is what I have
```
var conn = mysql.createConnection({
  socketPath: '/var/lib/mysql/mysql.sock',
  user: 'root',
  database: 'db'
});
```

**Comment by dougwilson** [comment] 2015-09-04 03:20
Hm, weird. I'm out of ideas, unfortunately. I marked this as "needs investigation", but I'm not sure I'll be able to investigate. If you have time and willing to investigate and report back with some information or even a PR with a fix, that  would be awesome :)

**Comment by dougwilson** [comment] 2015-11-30 04:19
Hi @vdraceil , I have done as much investigating as I could and cannot reproduce the issue as described. I'm closing this issue due to a lack of us being unable to reproduce and a lack of a PR to address the issue.

**Closed by dougwilson** 2015-11-30 04:19 UTC

**Comment by khizerrehands** [comment] 2017-03-12 20:49
@dougwilson  Can you please help me out ? i am accessing mysql database using node but it is giving me error shown in image. 

Node.js Code ScreenShot
![screenshot_5](https://cloud.githubusercontent.com/assets/26121221/23835798/499d9ba8-078f-11e7-8205-a5409d53417d.png)

Error ScreenShot
![screenshot_4](https://cloud.githubusercontent.com/assets/26121221/23835799/55bc1400-078f-11e7-89d4-ae4887a239ec.png)

Thank you!

**Comment by kai-koch** [comment] 2017-03-12 21:12
Since you are using windows, which versions of wampp you are using?
Can you access MySql with phpMyadmin and the same login you would use in Node?
Did you flush the user-cache or restart the mysql-server after altering the Password?

**Comment by kai-koch** [comment] 2017-03-12 21:17
Since you do not seem to be the the original poster: did you check for typos in the password?
