### ISSUE TITLE
Error: getaddrinfo ENOTFOUND all the time after enter a wrong host and then a valid host

### ISSUE THREAD

**Issue by Zilev** [felixge/node-mysql#1158] opened 2015-07-27 15:47 UTC
If I change the host to a wrong host, it shows this error "Error: getaddrinfo ENOTFOUND" which is ok, but after I change the connection to a valid host, I continues showing me the same error, mysql cann't recover and connect well again :cry: , somebody would help me please? I can't get why this happens,
the all error is:
```
Error: getaddrinfo ENOTFOUND
at errnoException (dns.js:37:11)
at Object.onanswer [as oncomplete] (dns.js:124:16)

```

**Comment by zilev** [comment] 2015-08-11 18:01
It seems like it start to fail only with wrong host name, because with ip adress is ok all the time, having the same test cases.

**Comment by dougwilson** [comment] 2015-08-11 19:19
I mean, DNS resolution is done by Node.js itself, and we don't do anything but pass your hostname down into Node.js network functions to create a socket.

Can you tell me what the output of the following command is (replacing "test.local" with your hostname you are getting ENOTFOUND for)?
```
$ node -pe 'require("dns").lookup("test.local",function(){console.dir(arguments)})'
```

**Comment by zilev** [comment] 2015-08-18 15:53
@dougwilson thanks for helping me, I having this output
```
{ callback: { [Function: asyncCallback] immediately: true },
  family: 0,
  hostname: 'test.local',
  oncomplete: [Function: onlookup] }
{ '0': 
   { [Error: getaddrinfo ENOTFOUND test.local]
     code: 'ENOTFOUND',
     errno: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'test.local' } }
```

**Comment by dougwilson** [comment] 2015-08-18 16:00
Hi @zilev , you need to replace "test.local" with your hostname you are getting ENOTFOUND for. Are you saying that you are getting ENOTFOUND for "localhost"?

**Comment by zilev** [comment] 2015-08-18 17:24
yeah I have ENOTFOUND error for localhost, but not exactly when host name is wrong, as I described before, following these steps:
* Enter well host name
* Enter a wrong host name (here shows ENOTFOUND error )
* Enter well host name (continues showing ENOTFOUND error) --> here is the problem shouldn't continue showing that error, only if I restart the server the error disapears.
But this happens only for host name, if I put ip address, everything is ok

**Comment by dougwilson** [comment] 2015-08-18 17:28
Hm, I'm not sure, and unable to reproduce locally based on what you said. All we do is take whatever you typed in and pass it to the Node.js core `net.createConnection` function, and we don't do any error caching. There is a possibility that it's a bug in the version of Node.js you are using. What version are you using?

**Comment by zilev** [comment] 2015-08-18 17:35
v0.12.7

**Comment by dougwilson** [comment] 2015-08-18 17:39
Hm, I'm still not able to reproduce. Can you try it with Node.js 0.10.40 to see if it goes away? If it's still there on 0.10.40, I think that would eliminate Node.js versions being different. It could also be our network/OS? I'm using Windows 7.

**Comment by zilev** [comment] 2015-08-18 19:35
my version node is v0.10.36, sorry my mistake, I'm using meteorjs which uses that version and cann't be changed, I'm using ubuntu 14.04

**Comment by dougwilson** [comment] 2015-10-25 18:23
I'm going to close this since I haven't been able to repro and, in the end, these errors come from Node.js core that we just surface through the error callbacks.

**Closed by dougwilson** 2015-10-25 18:23 UTC
Labels: needs investigation
