### ISSUE TITLE
Connection not closed as expect at poolCluster, and no way to known why pool end failed

### ISSUE THREAD

**Issue by iammapping** [felixge/node-mysql#1289] opened 2015-11-24 04:23 UTC
The connections of my production env always increase more than the config of `connectionLimit`. I guess it may meet some error while end the pool when remove node from poolCluster(error count exceed). I want to log these error, but the callback of `pool.end` is a noop https://github.com/felixge/node-mysql/blob/master/lib/PoolCluster.js#L256
It's better to emit error event:
```
node.pool.end(function(err) {
  if (err) self.emit('error', err);
});
```
thus I can log error out of the lib
```
poolCluster.on('error', function(err) {
  log(err);
});
```

**Comment by dougwilson** [comment] 2015-11-27 04:43
Hi! Unfortunately we won't be able to start emitting errors on the pool cluster in this major version, as it will cause process crashes in programs that did not crash prior (as without the emits in old version, it is unlikely anyone is listening to the event.

Ideally I would like to figure out the root of the issue and address that. Is there a way you can provide the following information? Version of Node.js, version of this module, and code I can use to reproduce the issue?

**Comment by iammapping** [comment] 2015-11-27 07:33
I'm trying to reproduce the issue at my development env, but no result. I occasionally received "too many connections" alarm from mysql server, sometimes interval 2 days, sometime interval many weeks. Our mysql servers located on AWS EC2, But only one has this issue. Once restart the nodejs server, the issue disappear. I think it may some uncertain factors lead closing connection failed, such as network. So I want to log what happens when pool end in poolCluster, but without modify the lib code.

**Comment by dougwilson** [comment] 2016-06-01 02:59
Hi @iammapping, I'm going to close this since I haven't hear back any additional information about how to reproduce to begin looking into this issue. Always let me know if you have additional information and I can always re-open!

**Closed by dougwilson** 2016-06-01 02:59 UTC
