### ISSUE TITLE
pool.end()

### ISSUE THREAD

**Issue by guypaskar** [felixge/node-mysql#1292] opened 2015-11-26 13:24 UTC
I have a pool and I call .end() but it seems that I still have a connection to the database when I call process.getActiveHandlers()

Is there anything else I need to do to completely destroy the pools connection to the database?

**Comment by intellent** [comment] 2015-11-26 15:46
I may have a similar problem. When I call `pool.end(callback)`, the callback is never triggered.

So my script never knows whether there was en error or not or if the pool is still available.

**Comment by guypaskar** [comment] 2015-11-26 16:09
I think mine actually resolved and it was my mistake :)

**Comment by dougwilson** [comment] 2015-11-27 04:40
Hi @guypaskar , sorry, my GitHub emails were not coming through for a bit so missed your issue. I'm going to close this if you have resolved your issue! If you're still having an issue, I would be happy to help, just post some information like Node.js version, version of this module, and example code to reproduce the issue :)

**Closed by dougwilson** 2015-11-27 04:40 UTC
Labels: question

**Comment by statico** [comment] 2016-02-08 21:51
@guypaskar Would you mind describing your mistake? I'm trying to debug something similar with node-mysql leaving connections open even after `pool.end()` (which doesn't take a callback, unlike a few of the other `end()` methods).

**Comment by dougwilson** [comment] 2016-02-16 00:09
@statico `pool.end` does indeed accept a callback. You can see this in our documentation: https://github.com/felixge/node-mysql#closing-all-the-connections-in-a-pool

**Comment by statico** [comment] 2016-02-16 00:14
@dougwilson Ah, I was confused -- Using a PoolCluster object returned by createPoolCluster(), its end() method doesn't take a callback. The problem eventually turned out to be some of our code not calling end() at all, which I diagnosed by looking at `process._getActiveHandles()` and seeing which ones were Sockets and what remote hosts and ports they were connected to.

**Comment by dougwilson** [comment] 2016-02-16 00:24
Hi @statico, weird, as even the Pool Cluster should accept a callback to the `.end` method: https://github.com/felixge/node-mysql/blob/master/lib/PoolCluster.js#L58

**Comment by dougwilson** [comment] 2016-02-16 00:25
Hi @statico, weird, as even the Pool Cluster should accept a callback to the `.end` method: https://github.com/felixge/node-mysql/blob/master/lib/PoolCluster.js#L58 The little bit of documentation for pool cluster in https://github.com/felixge/node-mysql#poolcluster even shows it taking a callback.

**Comment by statico** [comment] 2016-02-16 00:29
@dougwilson Ah, there's the problem -- we're on an ancient version of the module: https://github.com/felixge/node-mysql/blob/v2.0.1/lib/PoolCluster.js#L83

**Comment by dougwilson** [comment] 2016-02-16 00:32
Oh, haha. I forgot that was added in later, in fact, from a comment that it was inconsistent :) Looks like it came in version 2.6.0 (https://github.com/felixge/node-mysql/blob/master/Changes.md#v260-2015-03-24)
