### ISSUE TITLE
PROTOCOL_SEQUENCE_TIMEOUT in Node v4.2

### ISSUE THREAD

**Issue by TooBug** [felixge/node-mysql#1236] opened 2015-10-13 03:14 UTC
```
[Error: Query inactivity timeout]
PROTOCOL_SEQUENCE_TIMEOUT
```

I'm using this image <https://hub.docker.com/r/mhart/alpine-node/>, so not so sure if it's node-mysql's problem. Need confirm.

**Comment by kerihenare** [comment] 2015-10-13 03:44
Definitely seems to be an issue between **node-mysql** and **Node 4.2.0**. The following script works fine in 4.1.2 but gets a connection timeout in 4.2.0.

    var mysql      = require('mysql');

    var connection = mysql.createConnection({
        host:           'localhost',
        user:           'user',
        password:       'password',
        database:       'database'
    });
 
    connection.connect();
 
    connection.query('SELECT 1 + 1 AS solution', (error, rows, fields) => {
        if (error) {
            return console.log(error);
        }

        console.log('The solution is: ', rows[0].solution);
    });
 
    connection.end();

**Comment by dougwilson** [comment] 2015-10-13 03:47
By definition, 4.1.0 to 4.2.0 should be backwards-compatible. Please file a bug against Node.js for this so we can track here.

**Comment by dougwilson** [comment] 2015-10-13 03:49
Seems likely to be the bug https://github.com/nodejs/node/pull/3331

**Comment by dougwilson** [comment] 2015-10-13 04:00
I'll try to investigate the regression from Node.js 4.2 that is causing this sometime this week unless someone gets to it first :)

**Comment by fengmk2** [comment] 2015-10-13 05:19
https://github.com/nodejs/node/commit/63644dd1cd6e6765b52f60d54b0f94f7c69a8f79 introduced this bug.

Workaround: set `Sequence._idleTimeout = -1` instead of `undefined` https://github.com/felixge/node-mysql/blob/master/lib/protocol/sequences/Sequence.js#L30

**Comment by dougwilson** [comment] 2015-10-13 05:23
Looks like there is going to be a 4.2.1 tomorrow (https://github.com/nodejs/node/pull/3337), so it should be quick enough we don't need to introduce some kind of work-around for the bug.

**Comment by fengmk2** [comment] 2015-10-13 05:25
@dougwilson indeed.

**Comment by RobinQu** [comment] 2015-10-13 06:35
I should google before debugging this exception.......

**Comment by nmrony** [comment] 2015-10-13 06:43
@RobinQu I am also a victim of this.. Want to get update as soon as this issue is closed by @dougwilson

**Comment by Meekohi** [comment] 2015-10-13 14:39
Thanks, "everyone's favourite JavaScript feature". Having this issue also.

**Comment by clintfenton** [comment] 2015-10-13 15:33
+1

**Comment by clintfenton** [comment] 2015-10-13 15:35
Temporary fix from @fengmk2 worked for me to get things going again.  Looking forward to the repaired release.

**Comment by Jaykah** [comment] 2015-10-13 19:01
https://github.com/nodejs/node/pull/3337 has been merged

**Comment by dougwilson** [comment] 2015-10-13 19:07
Yes, and 4.2.1 has been released: https://nodejs.org/en/blog/release/v4.2.1/

**Closed by dougwilson** 2015-10-13 19:07 UTC
Labels: question

**Comment by Wikunia** [comment] 2015-10-14 12:09
I have the same error in v4.2.1 and I had to change `_idleTimeout` to `-1` to make it work.

**Comment by AdriVanHoudt** [comment] 2015-10-14 12:51
it should work on undefined see https://github.com/nodejs/node/pull/3331/files

**Comment by Wikunia** [comment] 2015-10-14 12:56
Thanks, not sure why this happens but well there is a fix, so it's okay for me.

**Comment by AdriVanHoudt** [comment] 2015-10-14 12:59
yeah it landed in 4.2.1 so it should work

**Comment by Meekohi** [comment] 2015-10-14 13:02
I can confirm v4.2.1 fixed this for me.

**Comment by dougwilson** [comment] 2015-10-14 14:32
Hi everyone, if you are getting this only in Node.js 4.2.0, it's because that version had a regression in timer code. You have to either downgrade to 4.1.0 or upgrade to 4.2.1.
