### ISSUE TITLE
Unrecoverable ECONNRESET after db failover

### ISSUE THREAD

**Issue by diversario** [felixge/node-mysql#1411] opened 2016-05-12 20:48 UTC
We have a MariaDB server that performs a failover every hour and we use `mysql` v2.10.2 to do an insert when user logs in.

I found that inserts succeed for some time after restarting the node app but once db connection is broken once it never goes back to normal:

```
[2016-05-12T20:41:09.470Z] ERROR: app/3018 on devserver.net (/lib/routes/index.js:687): Failed to create a record. (module=routes, err.code=ECONNRESET)
    Error: read ECONNRESET
        at errnoException (net.js:905:11)
        at TCP.onread (net.js:559:19)
        --------------------
        at Protocol._enqueue (/node_modules/mod/node_modules/mysql/lib/protocol/Protocol.js:141:48)
        at Connection.query (/node_modules/mod/node_modules/mysql/lib/Connection.js:201:25)
        at Connection.wrappedFunction [as query] (/node_modules/newrelic/lib/transaction/tracer/index.js:343:23)
        at /node_modules/mod/node_modules/knex/lib/dialects/mysql/index.js:92:18
        at tryCatcher (/node_modules/mod/node_modules/knex/node_modules/bluebird/js/main/util.js:26:23)
        at Promise._resolveFromResolver (/node_modules/mod/node_modules/knex/node_modules/bluebird/js/main/promise.js:480:31)
        at new Promise (/node_modules/mod/node_modules/knex/node_modules/bluebird/js/main/promise.js:70:37)
        at Client._query (/node_modules/mod/node_modules/knex/lib/dialects/mysql/index.js:88:12)
        at Client.query (/node_modules/mod/node_modules/knex/lib/client.js:136:24)
        at Runner.assign.query (/node_modules/mod/node_modules/knex/lib/runner.js:115:24)
        at Runner.tryCatcher (/node_modules/mod/node_modules/knex/node_modules/bluebird/js/main/util.js:26:23)
        at Runner.query (/node_modules/mod/node_modules/knex/node_modules/bluebird/js/main/method.js:15:34)
        at /node_modules/mod/node_modules/knex/lib/runner.js:43:21
        at /node_modules/mod/node_modules/knex/node_modules/bluebird/js/main/using.js:176:30
        at tryCatcher (/node_modules/mod/node_modules/knex/node_modules/bluebird/js/main/util.js:26:23)
        at Promise._settlePromiseFromHandler (/node_modules/mod/node_modules/knex/node_modules/bluebird/js/main/promise.js:507:31)
        at Promise._settlePromiseAt (/node_modules/mod/node_modules/knex/node_modules/bluebird/js/main/promise.js:581:18)
        at Promise._settlePromises (/node_modules/mod/node_modules/knex/node_modules/bluebird/js/main/promise.js:697:14)
        at Async._drainQueue (/node_modules/mod/node_modules/knex/node_modules/bluebird/js/main/async.js:123:16)
        at Async._drainQueues (/node_modules/mod/node_modules/knex/node_modules/bluebird/js/main/async.js:133:10)
        at Async.drainQueues (/node_modules/mod/node_modules/knex/node_modules/bluebird/js/main/async.js:15:14)
        at process._tickDomainCallback (node.js:502:13)
        at process.wrappedFunction (/node_modules/newrelic/lib/transaction/tracer/index.js:245:51)
```

**Comment by dougwilson** [comment] 2016-05-12 20:50
Weird. Any way you can provide full code and steps for me to reproduce the issue?

**Comment by diversario** [comment] 2016-05-12 20:54
Unfortunately, I cannot. I think the way to test this would be to setup a db with failover (or something that does to the connection the same thing failover does) and have a node app running with a connection to that db, performing inserts.

**Comment by diversario** [comment] 2016-05-12 20:56
Does `mysql` handle a case where a connection to the server is broken and then restored?

**Comment by dougwilson** [comment] 2016-05-12 20:58
So I've tried something simple along those lines and wasn't able to reproduce. The connection simply errored once and my code saw that since it was a fatal error, it made a new connection and reconnected. Using the pool does all that for you.

I'm not sure how to proceed without knowing what your code is doing. The stack trace was wrapping us in knex and promises, and I have no idea if that is where the issue is or not unless you can provide code & instructions on how to reproduce.

Let me know what you think I should do yo look into this.

**Comment by diversario** [comment] 2016-05-12 20:58
Ok, thanks, I'll try to dig up something more substantial.

**Comment by dougwilson** [comment] 2016-05-12 21:01
> Does  mysql  handle a case where a connection to the server is broken and then restored?

Depends on what your code is doing. If you create a connection, if that connection goes down, well, that connection object is not good, you have to create a new one. That's the purpose of why errors signal if they are fatal or not.

Pretty much it highly depends on your code, which is what makes it so important to get your code to understand what is happening. Also let me know if the readme is not very clear on how connection lifecycles work (a connection never reconnects, as documented).

**Comment by dougwilson** [comment] 2016-05-12 21:08
Basically, a `Connection` object here represents a connection to the MySQL server. If the connection dies, well, that object is dead, because you have to create a _new connection_ to the MySQL server. The pool, for example, manages all this for you, which is one of the main distinctions between a `Connection` and a `Pool` (even if the pool is just of 1 connection).

For example, if the `Connection` automatically reconnected, it can break app code, since any transaction the database may have been is has been rolled back and if it just blindly continued to execute further queries, they would either fail oddly, or end up with dangling data. The `Pool` and similar abstractions allows you to easily divide up all queries into their logical groups that won't wrap around connection losses, unlike a `Connection`.

If you are making queries on a `Connection` object, it means you are saying "perform this query on this connection" and it would be very unexpected if that guarantee was broken (for example, the session state will be completely reset randomly, with session variables going missing, `ROW_COUNT()` not working, etc).

**Comment by diversario** [comment] 2016-05-12 21:15
Oh, so maybe that's where there problem is – pooling. I believe knex has pooling by default (using `pool2` lib) but maybe it doesn't handle disconnects well. I'm going to try explicit pool config and see if that changes anything.

**Comment by ggurov** [comment] 2016-05-12 22:19
hi guys, DBA here from @diversario 's place. The VIP they connect to for writes moves between two hosts. It does that by the way of `linux-ha`. The same effect can be achieved by doing 

```
on master:
ip a del 10.1.20.25/23 dev eth0

on faliover:
ip a add 10.1.20.25/23 dev eth0
arping -U 10.1.20.25 -I eth0```

what i see on the DB is the connection stops sending queries (as it should), and eventually times out after the `wait_timeout` expires (600 seconds).

i suspect there's a missing `RST` back to the client when the connection goes away. Idle connections don't send data, and thus cannot time out until an event attempts to come through. This stale connection is somehow kept in the pool and not discarded  - BUT it reconnects. 

we've had cases where doing this flip and flip kept accumulating connections as the pool would add new connectiosn and not discard old ones, but that is unrelated to this issue.

**Comment by diversario** [comment] 2016-05-12 22:22
I found this issue https://github.com/tgriesser/knex/issues/1198 which might be what I'm experiencing. I'm currently trying out the advice given there to use a custom `ping`.

**Comment by dougwilson** [comment] 2016-05-12 23:48
I looked more into this and everything is operating as designed. The error `Error: read ECONNRESET` is unrecoverable, just as this module is designed. The `error` object we are giving back has a `fatal` property set to `true`.

The readme has a good section about server disconnects at https://github.com/felixge/node-mysql#server-disconnects

The issue you are describing really depending on your code, and if you are not making a new connection after a fatal error, then you... need to do that to open a new connection to the server.

Usually all of this is abstracted away by using our `Pool`, but as you said above, you are actually using `knex` and are not using our `Pool` object, so there isn't really anything we can do. The `knex` error linked to is right on the nail, and you have to set the pool to actually verify a connection pulled off the pool before using it (this module's `Pool` does that by default).

If you think that my closing this is in error, please provide full code & reproduction steps and we can always re-open and take a look. Another option is that since you are in possession of the code and can reproduce, create a pull request with a proposed solution :)

**Closed by dougwilson** 2016-05-12 23:48 UTC
Labels: needs investigation

**Comment by diversario** [comment] 2016-05-13 17:13
So, using a custom `ping` function as suggested in the `knex` thread fixed the issue, it looks like. This issue is because of `pool2`, not `mysql`.
